name             'supermarket-solo'
maintainer       'OurTownRentals.com'
maintainer_email 'evan@ourtownrentals.com'
license          'Apache 2.0'
description      'Installs and configures Supermarket.'
version          '0.1.0'

supports 'Ubuntu', '14.04'

recipe 'supermarket-solo::default', 'Installs and configures Supermarket.'

depends 'apt', '~> 2.4.0'
depends 'annoyances', '~> 1.0.0'
depends 'chef-solo-search', '~> 0.5.1'
depends 'firewall', '~> 0.11.8'
depends 'logrotate', '~> 1.6.0'
depends 'ntp', '~> 1.6.2'
depends 'openssh', '~> 1.3.4'
depends 'sudo', '~> 2.6.0'
depends 'supermarket', '~> 2.6.0'
depends 'timezone-ii', '~> 0.2.0'
depends 'users', '~> 1.7.0'
